src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mission__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Mission</label>
    <nameField>
        <label>Mission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Player</label>
    <nameField>
        <displayFormat>PLAYER{000}</displayFormat>
        <label>Player Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Push_Notification_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Enable_Push_Notifications__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, push notifications will be sent for any new game</description>
        <label>Enable Push Notifications</label>
        <type>Checkbox</type>
    </fields>
    <label>Push Notification Setting</label>
</CustomObject>

src/classes/NewMissionPushNotification.cls
public class NewMissionPushNotification {

    @future(callout=true)
    public static void sendNewMissionNotification(Set<Id> newMissionIds){
        if (Push_Notification_Setting__c.getOrgDefaults().Enable_Push_Notifications__c) {
            List<Mission__c> missions = [select id, Name, game__c from Mission__c where id in :newMissionIds]; 
            
            Set<Id> gameIds = new Set<Id>();
            for (Mission__c m : missions){
                gameIds.add(m.game__c);
            }
            
            //Query to see if the game(s) is still active and if it has any active players
            //to send notifications to
            List<Player__c> activePlayers = [select id from Player__c 
                                             where game__c in :gameIds 
                                             and game__r.End_date_time__c > :datetime.now()];
            
            if (activePlayers.size() == 0)
                return;
                                   
            UAPushNotificationSvc svc = new UAPushNotificationSvc('Cloud Hunter');
            for (Mission__c m : missions)
            {
                UAPushNotification notification = new UAPushNotification(null , null, null,
                                                                         'A new mission has been added',
                                                                          null);
                try
                {
                    //svc.sendAndroidBroadcastNotification(notification);
                    svc.sendiOSBroadcastNotification(notification);
                }
                catch(UAException e)
                {
                    System.debug('Could not send Urban Airship notification');
                }   
            }                
        }
	}
}